### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by TormentedSoul666** [EntySec/HatSploit#51]
Just saw your comment at RomBruter and you're right, your framework is much more versatile, up-to-date and very well modulary written. I'll check it out in depth and see if I can contribute something.

**Comment by enty8080** [comment]
Hello, @TormentedSoul666

Thank you very much for your rating.
I will be glad if you recommend it to someone or just spread the word that this is a good framework.

If you want to read more about HatSploit and how to use it, just open documentation in GitHub wiki - https://github.com/EntySec/HatSploit/wiki. There you can also find how to pentest D-Link routers, Windows systems and other platforms.

HatSploit has small database of modules because I am working alone, but I promise, I'll add more exploits and payloads soon.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by wr0x00** [comment]
So I do.This project is rich in prospects and innovation, and I look forward to it becoming the second metasploit!

**Comment by wr0x00** [comment]
So do I.This project is rich in prospects and innovation, and I look forward to it becoming the second metasploit!

**Comment by enty8080** [comment]
@wr0x00 More documentation coming soon here - https://docs.hatsploit.com/
